In [4]:
import numpy as np
my_list =  [12.23, 13.32, 100, 36.32] 
arr = np.array(my_list)
print(arr)

[ 12.23  13.32 100.    36.32]


In [9]:
# Create 3x3 Matrix (2?10)
arr3d = np.arange(2,11).reshape(3,3)
print(arr3d)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [15]:
# Null Vector (10) & Update Sixth Value
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
# np.zeros((2, 3))                 # 2x3 array of zeros
arrzero = np.zeros(10)
arrzero[5] = 11
print(arrzero)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [17]:
# Array from 12 to 38
# Write a NumPy program to create an array with values ranging from 12 to 38.
arr1 = np.arange(12,39)
print(arr1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [22]:
# Convert Array to Float Type
# Write a NumPy program to convert an array to a floating type.
arr = np.array([1,2,3,4])
float_arr =  arr.astype(float)
print(float_arr.dtype)
float_arr

float64


array([1., 2., 3., 4.])

In [23]:
# Celsius to Fahrenheit Conversion
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

# Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

# Expected Output:

# Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]


import numpy as np
celsius_values = np.array([0, 12, 45.21, 34, 99.91])
fahrenheit_values = np.array([0, 12, 45.21, 34, 99.91, 32])
c_to_f= (celsius_values*9/5) + 32
f_to_c = (fahrenheit_values-32)*5/9

c_to_f = np.round(c_to_f, 2)
f_to_c = np.round(f_to_c, 2)



print("Values in Fahrenheit degrees:", c_to_f)
print("Values in Centigrade degrees:", f_to_c)


Values in Fahrenheit degrees: [ 32.    53.6  113.38  93.2  211.84]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [27]:
#  Append Values to Array (Do self-tudy)
# Write a NumPy program to append values to the end of an array.

# Expected Output:

# Original array: [10, 20, 30]

# After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


import numpy
orgarr = np.array([10, 20, 30])
orgarr
new_arr = np.append(orgarr,[40,50,60,70, 80, 90])
print(new_arr)

[10 20 30 40 50 60 70 80 90]


In [35]:
#  Array Statistical Functions (Do self-tudy)
# Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.
import numpy as np\

arr1 = np.random.randint(1,100, 10)
print(arr1)
print(arr1.min())
print(arr1.max())
print(arr1.mean())
print(arr1.std())

[73 73 62  9 59  9 71 22 49 90]
9
90
51.7
27.280212609142183


In [40]:
#  Find min and max
# Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np
arr2 = np.random.randint(1,100, (10,10))
print(arr2)
print(arr2.max())
print(arr2.min())

[[35 13 81 27 92  6 40 60 56 14]
 [76 33 11 88 80 93 59 40 58 60]
 [49 82 90 40 85 18 91 54 12 53]
 [67 47 73 58 29 33 70 27 63 14]
 [78 71 18 95 97 73 81 95 97 59]
 [64  3 79 45 35 91 84 34 57 38]
 [39 90 36  5 31 32 86  8 59 60]
 [34 38  5 98 58 88  6 26 59  6]
 [98 73 72 14 41 28 51 75 20 35]
 [33 84 64 97 44 47 71 66 97 62]]
98
3


In [44]:
import numpy as np
arr3D = np.random.randint(1,20, (3,3,3))

arr3D

array([[[ 6, 18, 13],
        [ 7, 11, 14],
        [11, 14,  6]],

       [[ 4,  9,  6],
        [17, 10,  3],
        [16,  9, 14]],

       [[ 6, 15, 13],
        [16, 18, 10],
        [19, 15, 16]]], dtype=int32)